# Generated by Django 6.0.3 on 2026-03-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participants',
            new_name='members',
        ),
    ]
